# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3

    steps:
      - checkout

      - restore_cache:
          keys:
          - deps-{{ checksum "requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: deps-{{ checksum "requirements.txt" }}

      - run:
          name: run linting and metrics
          command: |
            python3 -m venv venv
            . venv/bin/activate
            flake8 . --output-file test-reports --tee --statistics

      - store_artifacts:
          path: test-reports
          destination: test-reports
